### PR TITLE
Update the lib with `@mtkmodel`

### PR DESCRIPTION
**Pull request by ven-k**
This PR updates the lib with `@mtkmodel` DSL.

- The API remains same, except for `ShiHeart`;  `LV_V₀` is now `LV.V₀` and all args follow the same pattern. As subcomponent args can be accessed with `A.B` syntax, this change is introduced.
- In tests, "Shi Model - Complex" is updated with a `mtkmodel` based circulatory system.
- `Compliance`, `VariableCompliance`, Elastance and `ShiValve` will be updated with a follow up PR. The first three need a way to set default values to conditional parameters and `ShiValve` needs a way to set `continuous_events.` PRs adding both are currently open upstream. Once they are merged I'll update them here.

### CODE REVIEW

**Comment by ven-k** [comment]
The earlier syntax of extending components was `@extend = var1, var2 = Component()`. In a later version of MTK, that was changed to `@extend Component()`. This later version must have Julia compat as 1.9. So the CI has failed with 1.8.

Shall I update CI to 1.9, 1.10 (current latest) and nightly?

Also, the error on nightly is unrelated to this PR.

**Comment by TS-CUBED** [comment]
Thanks a lot for this. I had this on my todo list before Christmas, but put it on the back burner, because I did not know how to handle the conditionals. I will merge this PR now and once the other elements are adapted and MTK 9 has been tested with this (I hope to get to that in March), will release a new version.

**Comment by TS-CUBED** [comment]
> Compliance, VariableCompliance, Elastance and ShiValve will be updated with a follow up PR. The first three need a way to set default values to conditional parameters and ShiValve needs a way to set continuous_events. PRs adding both are currently open upstream. Once they are merged I'll update them here.

I haven't followed upstream recently due to other commitments. Do we have these features (conditional parameters/branching, and continuous events) in the @mtkmodel framework?

**Comment by ven-k** [comment]
Yes; those features are now part of MTK@v9+.

**Pull request merged**
